import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs'

// Point Vite directly at the shared TypeScript source so it never touches the
// CJS dist. This avoids esbuild's unreliable CJS→ESM getter re-export handling.
const sharedSrc = fileURLToPath(new URL('../../packages/shared/index.ts', import.meta.url))

// ── Dev-only: POST /dev/save-splendor-cards writes splendorCards.ts ──────────
function splendorCurationPlugin(): Plugin {
  return {
    name:  'splendor-curation-dev',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/dev/save-splendor-cards', (req, res, next) => {
        if (req.method !== 'POST') return next()

        let body = ''
        req.on('data', (chunk: Buffer) => { body += chunk.toString() })
        req.on('end', () => {
          try {
            type RawCard = {
              id: string; level: 1 | 2 | 3; spriteIndex: number
              gemProduced: string; prestigePoints: number
              cost: Record<string, number>
            }
            type RawNoble = {
              id: string; prestigePoints: number
              requires: Record<string, number>
            }
            const { cards, nobles } = JSON.parse(body) as { cards: RawCard[], nobles: RawNoble[] }

            const cardLine = (c: RawCard) => {
              const costParts = Object.entries(c.cost)
                .filter(([, v]) => v > 0)
                .map(([k, v]) => `${k}: ${v}`)
                .join(', ')
              return `  { id: '${c.id}', level: ${c.level}, spriteIndex: ${c.spriteIndex}, gemProduced: '${c.gemProduced}', prestigePoints: ${c.prestigePoints}, cost: { ${costParts} } },`
            }

            const nobleLine = (n: RawNoble) => {
              const reqParts = Object.entries(n.requires)
                .filter(([, v]) => v > 0)
                .map(([k, v]) => `${k}: ${v}`)
                .join(', ')
              return `  { id: '${n.id}', prestigePoints: ${n.prestigePoints}, requires: { ${reqParts} } },`
            }

            const block = (lvl: 1 | 2 | 3, name: string) =>
              `export const ${name}: SplendorCard[] = [\n` +
              cards.filter(c => c.level === lvl).map(cardLine).join('\n') +
              `\n]`

            const noblesBlock =
              `export const NOBLES: SplendorNoble[] = [\n` +
              nobles.map(nobleLine).join('\n') +
              `\n]`

            const ts =
              `import type { SplendorCard, SplendorNoble } from './splendor.js'\n\n` +
              `// Generated by /splendor-curation — do not edit manually\n` +
              block(1, 'LEVEL1_CARDS') + '\n\n' +
              block(2, 'LEVEL2_CARDS') + '\n\n' +
              block(3, 'LEVEL3_CARDS') + '\n\n' +
              noblesBlock + '\n'

            const outPath = fileURLToPath(new URL('../../packages/shared/splendorCards.ts', import.meta.url))
            fs.writeFileSync(outPath, ts, 'utf-8')

            res.setHeader('Content-Type', 'application/json')
            res.statusCode = 200
            res.end(JSON.stringify({ ok: true, path: outPath }))
          } catch (err) {
            res.statusCode = 500
            res.end(JSON.stringify({ error: String(err) }))
          }
        })
      })
    },
  }
}

export default defineConfig({
  plugins: [react(), tailwindcss(), splendorCurationPlugin()],
  // Serve packages/client/assets/ as the static public root so that
  // /splendor/fichas/20.png, /splendor/atlases/32.jpg, etc. resolve correctly.
  publicDir: 'assets',
  resolve: {
    alias: {
      '@gamengine/shared': sharedSrc,
    },
  },
  server: {
    fs: {
      // Allow Vite's dev server to read files from the monorepo root upward.
      allow: ['../..'],
    },
    proxy: {
      '/socket.io': {
        target: 'http://localhost:3000',
        ws: true,
      },
    },
  },
})
